<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.8.4">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.8.4">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.rules.ZeroR" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayes" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.lazy.IBk" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">1</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">0</object>
            <object class="java.lang.String" name="4">-A</object>
            <object class="java.lang.String" name="5">weka.core.neighboursearch.LinearNNSearch -A &quot;weka.core.EuclideanDistance -R first-last&quot;</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-8</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.CostSensitiveClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-cost-matrix</object>
            <object class="java.lang.String" name="1">[0.0 1.0; 4.0 0.0]</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.CostSensitiveClassifier" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-cost-matrix</object>
            <object class="java.lang.String" name="1">[0.0 1.0; 4.0 0.0]</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.lazy.IBk</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">0</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">weka.core.neighboursearch.LinearNNSearch -A &quot;weka.core.EuclideanDistance -R first-last&quot;</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.CostSensitiveClassifier" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-cost-matrix</object>
            <object class="java.lang.String" name="1">[0.0 1.0; 4.0 0.0]</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.Logistic</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-R</object>
            <object class="java.lang.String" name="8">1.0E-8</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">-1</object>
            <object class="java.lang.String" name="11">-num-decimal-places</object>
            <object class="java.lang.String" name="12">4</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.CostSensitiveClassifier" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-cost-matrix</object>
            <object class="java.lang.String" name="1">[0.0 1.0; 4.0 0.0]</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-P</object>
            <object class="java.lang.String" name="8">100</object>
            <object class="java.lang.String" name="9">-I</object>
            <object class="java.lang.String" name="10">100</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-K</object>
            <object class="java.lang.String" name="14">0</object>
            <object class="java.lang.String" name="15">-M</object>
            <object class="java.lang.String" name="16">1.0</object>
            <object class="java.lang.String" name="17">-V</object>
            <object class="java.lang.String" name="18">0.001</object>
            <object class="java.lang.String" name="19">-S</object>
            <object class="java.lang.String" name="20">1</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_id.remove_attrs_with_missing_values.arff</object>
      <object class="java.io.File" name="1">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_id.remove_attrs_with_missing_values.pca.arff</object>
      <object class="java.io.File" name="2">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_id.remove_attrs_with_missing_values.pca.smote.arff</object>
      <object class="java.io.File" name="3">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_id.remove_attrs_with_missing_values.smote.arff</object>
      <object class="java.io.File" name="4">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_outliers.remove_id.remove_attrs_with_missing_values.arff</object>
      <object class="java.io.File" name="5">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_outliers.remove_id.remove_attrs_with_missing_values.pca.arff</object>
      <object class="java.io.File" name="6">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_outliers.remove_id.remove_attrs_with_missing_values.pca.smote.arff</object>
      <object class="java.io.File" name="7">preprocessed/CWData_train.remove_missing.reduce_duplicates.remove_outliers.remove_id.remove_attrs_with_missing_values.smote.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">10</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">experiment.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">/home/matthew/gdrive/CS/data-mining/coursework/matthew/modeling/experiment.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
